#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 03 01:44:32 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=\u00A7l\u00A7fAstral\u00A7dCore.zip
