#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 12 13:54:28 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=10
shaderPack=\u00A7l\u00A7fAstral\u00A7dCore.zip
