version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
kubejs = true
create_simple_ore_doubling = true
gyro = true
createfood = true
farmersdelight = true
magnumtorch = true
molten_vents = true
chipped = true
croptopia = true
arsdelight = true
create = true
numismatics = true
aeronautics = true
easymagic = true
simulated = true
create_aeronautics_toolgun = true
morebridges = true
quark = true
natures_spirit = true
easyanvils = true
biomeswevegone = true
visualworkbench = true
copycats = true
minecraft = true
reestrogen = true
paraglider = true
lootr = true
comforts = true
mcwpaths = true
ars_technica = true
create_jetpack = true
envelope = true
sophisticatedstorage = true
mcwbridges = true
aether = true
sliceanddice = true
portals = true
ars_nouveau = true
handcrafted = true
ftbquests = true
diagonalfences = true
sauce = true
rechiseledcreate = true
ars_creo = true
sophisticatedbackpacks = true
offroad = true
rechiseled = true
create_power_loader = true
